# Generated by Django 5.2 on 2025-04-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('co', models.FloatField()),
                ('no2', models.FloatField()),
                ('nh3', models.FloatField()),
                ('h2', models.FloatField()),
                ('ch4', models.FloatField()),
                ('c2h5oh', models.FloatField()),
            ],
        ),
    ]
