# Generated by Django 5.2 on 2025-04-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasreading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
