# Generated by Django 5.2 on 2025-04-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_alter_gasreading_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasreading',
            old_name='c2h5oh',
            new_name='CH4_ppm',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='ch4',
            new_name='CO_ppm',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='co',
            new_name='Ethanol_ppm',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='h2',
            new_name='H2_ppm',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='nh3',
            new_name='NH3_ppm',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='no2',
            new_name='NO2_ppm',
        ),
        migrations.AddField(
            model_name='gasreading',
            name='warnings',
            field=models.CharField(default='No warnings', max_length=255),
        ),
    ]
