# Generated by Django 5.2 on 2025-04-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_rename_c2h5oh_gasreading_ch4_ppm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasreading',
            old_name='CH4_ppm',
            new_name='c2h5oh',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='CO_ppm',
            new_name='ch4',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='Ethanol_ppm',
            new_name='co',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='H2_ppm',
            new_name='h2',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='NH3_ppm',
            new_name='nh3',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='NO2_ppm',
            new_name='no2',
        ),
        migrations.RemoveField(
            model_name='gasreading',
            name='warnings',
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
