# Generated by Django 5.2 on 2025-05-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_rename_ch4_ppm_gasreading_c2h5oh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasreading',
            old_name='c2h5oh',
            new_name='C2H5OH',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='ch4',
            new_name='CH4',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='h2',
            new_name='H2',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='nh3',
            new_name='NH3',
        ),
        migrations.RenameField(
            model_name='gasreading',
            old_name='no2',
            new_name='NO2',
        ),
        migrations.AddField(
            model_name='gasreading',
            name='C2H5OH_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='CH4_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='CO_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='H2_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='NO2_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='humidity_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='temperature_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
