# Generated by Django 5.2 on 2025-05-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_rename_c2h5oh_gasreading_c2h5oh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasreading',
            name='co',
        ),
        migrations.AddField(
            model_name='gasreading',
            name='device_error',
            field=models.CharField(default='0000.00', max_length=20),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='device_id',
            field=models.CharField(default='ABX2345JK', max_length=100),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='device_latitude',
            field=models.CharField(default='51.5669854', max_length=30),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='device_longitude',
            field=models.CharField(default='0.2127605', max_length=30),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='device_rfid',
            field=models.CharField(default='261AF283930334', max_length=100),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='device_status',
            field=models.CharField(default='OK', max_length=20),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='modem_cell_id',
            field=models.CharField(default='123456', max_length=50),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='modem_dl',
            field=models.CharField(default='20 mbps', max_length=20),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='modem_ip',
            field=models.CharField(default='192.168.0.101', max_length=50),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='modem_mcc',
            field=models.CharField(default='404', max_length=10),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='modem_mnc',
            field=models.CharField(default='45', max_length=10),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='modem_network_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='modem_rssi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='modem_status',
            field=models.CharField(default='OK', max_length=10),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='modem_ul',
            field=models.CharField(default='10 mbps', max_length=20),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='C2H5OH',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='CH4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='H2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='NH3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='NO2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='CO',
            field=models.FloatField(default=0.0),
        ),
    ]
